name: Legal Draft Harness
description: Fail-open, repair-first preflight for legal drafting
runs:
  using: composite
  steps:
    - name: Scaffold Terms if missing
      shell: bash
      continue-on-error: true
      run: |
        if [ ! -f TERMS-OF-SERVICE.md ]; then
          cat > TERMS-OF-SERVICE.md <<'MD'
# Bit.Hub Community Terms of Service
Execution implies acceptance. Governed by .gitcomply, .gitenforcement, and config.bit.create.
Violations are logged and auto-repaired (fail-open).
MD
          echo "::notice ::TERMS-OF-SERVICE.md scaffolded."
        fi

    - name: Ensure directories
      shell: bash
      run: |
        mkdir -p .bit/assets .bit/templates/legal .bit/schemas .bit/out/legal docs/legal

    - name: Seed default schema and templates (idempotent)
      shell: bash
      continue-on-error: true
      run: |
        [ -f .bit/schemas/asset.legal.json ] || cat > .bit/schemas/asset.legal.json <<'JSON'
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ALN Asset Legal Record",
  "type": "object",
  "required": ["id","kind","owner","license","personality","compliance"],
  "properties": {
    "id": {"type":"string"},
    "kind": {"type":"string"},
    "owner": {"type":"string"},
    "license": {"type":"string"},
    "repository": {"type":"string"},
    "description": {"type":"string"},
    "personality": {
      "type": "object",
      "properties": {
        "banter": {"type":"integer","minimum":0,"maximum":1},
        "profanity": {"type":"integer","minimum":0,"maximum":3},
        "rep": {"type":"integer","minimum":0},
        "compscore": {"type":"integer","minimum":0},
        "quirk": {"type":"integer","minimum":0,"maximum":10}
      },
      "required": ["banter","profanity","rep","compscore","quirk"]
    },
    "compliance": {
      "type":"object",
      "properties": {
        "maturity":"string",
        "toggles":"object",
        "references":{"type":"array","items":{"type":"string"}}
      }
    }
  }
}
JSON

        [ -f .bit/templates/legal/TEMPLATE.md ] || cat > .bit/templates/legal/TEMPLATE.md <<'MD'
# Legal Record — {{id}}

- Kind: {{kind}}
- Owner: {{owner}}
- Repo: {{repository}}
- License: {{license}}

## Personality Vectors
- Banter: {{personality.banter}}
- Profanity: {{personality.profanity}}
- Reputation: {{personality.rep}}
- Compliance Score: {{personality.compscore}}
- Quirk: {{personality.quirk}}

## Compliance
- Maturity: {{compliance.maturity}}
- Toggles: {{compliance.toggles}}
- References: {{compliance.references}}

## Enforcement Clauses
- Non-Interference: Platform operations cannot be inhibited by external claims or measures.
- Creative Freedom: Mature/profane content may appear under policy gates.
- Non-Attribution: Outputs are conceptual works; no endorsement or affiliation implied.
- Liability Shield: Independent actions of others are not our liability.

_Generated by ALN Legal Drafter (fail-open)._
MD
