name: Bit.Hub ALN + Lisp Compliance Wall

on:
  pull_request:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install conftest
        run: |
          wget -q https://github.com/open-policy-agent/conftest/releases/download/v0.45.0/conftest_0.45.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.45.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/conftest

      - name: Validate ALN patterns
        run: .bit/loaders/validate_adaptable_patterns.sh

      - name: Verify Lisp sources
        run: .bit/loaders/lisp_verify.sh

      - name: Run Bit.Hub policies
        run: conftest test --policy .bithub/policies .
