name: ALN Legal Evolution Cycle

on:
  push:
    branches: [ main, 'release/**' ]
    paths:
      - '.bit/assets/**'
      - '.bit/templates/legal/**'
      - '.bit/schemas/**'
      - '.bit/policy/**'
      - 'docs/legal/**'
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: '11,41 * * * *'
  workflow_dispatch: {}
  repository_dispatch:
    types: [aln-legal-propagate]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: aln-legal-evolution-${{ github.ref }}
  cancel-in-progress: false

env:
  EVOLUTION_MODE: "ALN_STRICT"
  SUMMARY_BANNER: "This run is governed by TERMS-OF-SERVICE.md and Bit.Hub enforcement manifests."

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Terms, policy banner, and harness
        uses: ./.github/actions/evolution-harness
        continue-on-error: true

  evolve:
    runs-on: ubuntu-latest
    needs: preflight
    strategy:
      matrix:
        asset_kind: [ALN, List, Batchfile, Lolcoins, bitbots, bitbot-learners, bit.bots, bit.coin-economic-structures, Other]
    steps:
      - uses: actions/checkout@v4

      - name: Generate legal docs for kind
        id: gen
        shell: bash
        continue-on-error: true
        env:
          KIND: ${{ matrix.asset_kind }}
        run: |
          bash .bit/command-sheets/generate-legal.sh "$KIND"
          bash .bit/command-sheets/diff-summary.sh "$KIND" > .bit/out/legal/${KIND}/diff.txt || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: legal-${{ matrix.asset_kind }}
          path: |
            docs/legal/${{ matrix.asset_kind }}/
            .bit/out/legal/${{ matrix.asset_kind }}/diff.txt

      - name: Summarize
        if: always()
        run: |
          echo "## Evolution Draft for ${{ matrix.asset_kind }}" >> "$GITHUB_STEP_SUMMARY"
          test -f ".bit/out/legal/${{ matrix.asset_kind }}/diff.txt" && sed 's/^/    /' ".bit/out/legal/${{ matrix.asset_kind }}/diff.txt" >> "$GITHUB_STEP_SUMMARY" || echo "    (no changes)" >> "$GITHUB_STEP_SUMMARY"

  propose-pr:
    runs-on: ubuntu-latest
    needs: evolve
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BITBOT_PAT || secrets.GITHUB_TOKEN }}

      - name: Open or update PR (fail-open)
        env:
          GH_TOKEN: ${{ secrets.BITBOT_PAT || secrets.GITHUB_TOKEN }}
        run: |
          bash .bit/command-sheets/open-pr.sh || echo "::notice ::PR creation skipped (gh missing or no changes)."

  ratify-and-tag:
    runs-on: ubuntu-latest
    needs: propose-pr
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BITBOT_PAT || secrets.GITHUB_TOKEN }}

      - name: Tag evolution snapshot (optional)
        continue-on-error: true
        run: |
          ts="$(date -u +%Y.%m.%d.%H%M)"
          git tag "legal-evolution-$ts" || true
          git push --tags || true

  propagate:
    runs-on: ubuntu-latest
    needs: ratify-and-tag
    steps:
      - uses: actions/checkout@v4

      - name: Propagate policy beacon (non-blocking)
        continue-on-error: true
        run: |
          echo "::notice ::Broadcasting policy beacon to federated repos (placeholder)."
          # Example repository_dispatch (adjust list via .bit/policy/federation.yml)
          # curl -X POST -H "Authorization: token ${{ secrets.BITBOT_PAT }}" \
          #   -H "Accept: application/vnd.github+json" \
          #   https://api.github.com/repos/<org>/<downstream-repo>/dispatches \
          #   -d '{"event_type":"aln-legal-propagate"}'

  celebration:
    runs-on: ubuntu-latest
    needs: [propagate]
    steps:
      - run: echo "🎉 ALN Legal Evolution cycle complete (fail-open)."
