name: Bit.Hub Policy Bootstrap and Runner Training — Full Compliance

on:
  workflow_dispatch:
    inputs:
      power_threshold:
        description: "standard | strict | paranoid"
        type: choice
        default: "standard"
        options: [ "standard", "strict", "paranoid" ]
  schedule:
    - cron: "19 3 * * *"

permissions:
  contents: read

concurrency:
  group: bithub-bootstrap-train-${{ github.ref }}
  cancel-in-progress: false

env:
  BIT_HUB_REPO_URL: "https://github.com/Doctor0Evil/Bit.Hub.git"
  REPORT_DIR: ".bithub/reports"
  POLICY_DIR: ".bithub/policy"
  OPA_VERSION: "0.64.1"
  POWER_THRESHOLD: ${{ inputs.power_threshold || vars.POWER_THRESHOLD || 'standard' }}

jobs:
  bootstrap_and_train:
    name: Bootstrap policies and educate runner
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Sync canonical Bit.Hub policies (non-blocking)
        run: |
          set +e
          if git ls-remote "$BIT_HUB_REPO_URL" &>/dev/null; then
            git clone --depth=1 "$BIT_HUB_REPO_URL" /tmp/bithub
            rsync -av --ignore-existing /tmp/bithub/.bithub/policy/ .bithub/policy/
            rsync -av --ignore-existing /tmp/bithub/.bit/schemas/ .bit/schemas/
          else
            echo "::warning::Canonical repo unreachable — using local policies"
          fi
          set -e

      - name: Install OPA
        run: |
          BIN="$HOME/.local/bin"; mkdir -p "$BIN"
          curl -fsSL -o "$BIN/opa" "https://openpolicyagent.org/downloads/v${OPA_VERSION}/opa_linux_amd64_static"
          chmod +x "$BIN/opa"; echo "$BIN" >> $GITHUB_PATH

      - name: Run Bit.Hub policy trainer (education functions)
        id: trainer
        uses: ./.github/actions/bit-hub-policy-trainer
        with:
          power_threshold: ${{ env.POWER_THRESHOLD }}

      - name: Evaluate runner against policy (advisory)
        run: |
          INPUT="$(cat "${{ steps.trainer.outputs.report }}")"
          printf '%s\n' "$INPUT" > /tmp/runner.json
          opa eval -f pretty -I -d "${POLICY_DIR}" -i /tmp/runner.json 'data.bithub.runner' || true

      - name: Upload training artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bithub-runner-training
          path: .bithub/reports
          if-no-files-found: warn
