name: Bit.Hub Cross-Repo Governance Orchestrator
on:
  workflow_run:
    workflows:
      - Bit.Hub Pipeline Supremacy CI
      - Bit.Hub Policy Scorecard Gate
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: read

concurrency:
  group: xrepo-orchestrator-${{ github.ref }}
  cancel-in-progress: false

env:
  BITHUBREPOURL: https://github.com/Doctor0Evil/Bit.Hub.git
  POWERTHRESHOLD: paranoid

jobs:
  sync_and_correct:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync Bit.Hub Policies & Schemas
        run: |
          set -e
          if git ls-remote $BITHUBREPOURL &> /dev/null; then
            git clone --depth=1 $BITHUBREPOURL tmpbithub
            rsync -av --ignore-existing tmpbithub/.bithubpolicy .bithubpolicy
            rsync -av --ignore-existing tmpbithub/.bitschemas .bitschemas
          else
            echo "warning: Bit.Hub repo unreachable, using local copies"
          fi

      - name: MetaCorrector v3
        uses: ./github/workflows/bit-hub-meta-corrector-v3.yml
        with:
          autofix: true
          powerthreshold: ${{ env.POWERTHRESHOLD }}
          targetref: main

  redeploy_if_clean:
    needs: sync_and_correct
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check MetaCorrector v3 Report
        run: |
          REPORT=.bithubreports/meta-corrector-v3.ndjson
          if [[ -f "$REPORT" ]]; then
            DENY=$(jq '.deny | length' "$REPORT")
            WARN=$(jq '.warn | length' "$REPORT")
            if [[ "$DENY" == "0" && ("$POWERTHRESHOLD" == "standard" || "$WARN" == "0") ]]; then
              echo "No blocking issues, triggering production deploy"
              gh workflow run "Bit.Hub Secure CD Supremacy Progressive Delivery" -f environment=production -f powerthreshold="$POWERTHRESHOLD"
            else
              echo "Blocking issues remain; skipping redeploy"
            fi
          else
            echo "No report found; skipping redeploy"
          fi

  audit_and_cache:
    needs: redeploy_if_clean
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: BitBot Compliance Learning Enforcement
        uses: ./github/workflows/bitbotcompliancelearning.yml
        with:
          retention: 5
