name: BitBot Compliance & Build

on:
  workflow_dispatch:
    inputs:
      power_threshold:
        description: "standard | strict | paranoid"
        type: choice
        default: "standard"
        options: [standard, strict, paranoid]
  push:
    branches: ["main"]
    paths:
      - '.bithub/policies/**'
      - 'ALN/**/*.lisp'
      - 'Batch/**/*.bat'
      - 'LOL_LANG/**/*.lol'
      - 'virtual.data.banks/**'
      - 'fan.asia/AIFantasia/**'
      - 'virta-net/**'
  schedule:
    - cron: "23 3 * * *" # Daily at 03:23 UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  bitbot:
    runs-on: ubuntu-latest
    env:
      BIT_HUB_REPO_URL: https://github.com/Doctor0Evil/Bit.Hub.git
      POWER_THRESHOLD: ${{ inputs.power_threshold || 'standard' }}
    steps:
      - uses: actions/checkout@v4

      - name: Install yq, opa, gh
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq curl git
          curl -fsSL -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          chmod +x /usr/local/bin/yq
          curl -fsSL -o /usr/local/bin/opa https://openpolicyagent.org/downloads/v0.64.1/opa_linux_amd64_static
          chmod +x /usr/local/bin/opa
          curl -fsSL https://raw.githubusercontent.com/cli/cli/trunk/script/install.sh | sh -s -- -b /usr/local/bin

      - name: Sync Bit.Hub rules
        run: |
          TMP=$(mktemp -d)
          git clone --depth=1 "$BIT_HUB_REPO_URL" "$TMP"
          cp -f "$TMP/.gitcomply" .gitcomply
          cp -f "$TMP/.gitenforcement" .gitenforcement || true
          mkdir -p .bit
          cp -f "$TMP/.bit/config.bit.create" .bit/config.bit.create
          mkdir -p .bithub/policy
          rsync -a --ignore-existing "$TMP/.bithub/policy/" .bithub/policy/

      - name: Apply config.bit.create defaults
        run: |
          for wf in $(find .github/workflows -type f -name '*.yml' -o -name '*.yaml'); do
            yq -i '.permissions = (.permissions // load(".bit/config.bit.create").defaults.workflow.permissions)' "$wf"
            yq -i '.concurrency = (.concurrency // load(".bit/config.bit.create").defaults.workflow.concurrency)' "$wf"
            yq -i '.jobs |= with_entries(.value."timeout-minutes" = (.value."timeout-minutes" // load(".bit/config.bit.create").defaults.workflow.timeout-minutes))' "$wf"
            yq -i '.. | select(tag == "!!str") |= sub("actions/checkout@v[12]$"; load(".bit/config.bit.create").defaults.workflow.checkout_version)' "$wf"
          done

      - name: Evaluate workflows
        run: |
          mkdir -p .bithub/reports
          for wf in $(find .github/workflows -type f -name '*.yml' -o -name '*.yaml'); do
            jq -n --arg path "$wf" --argjson wf_json "$(yq -o=json '.' "$wf")" \
              '{path:$path, workflow:$wf_json}' > /tmp/input.json
            opa eval -f json -I -d ".bithub/policy" -i /tmp/input.json 'data.bithub.workflow' \
              | jq -c '.result[].expressions[].value' --argfile input /tmp/input.json \
              >> .bithub/reports/workflow-policy.ndjson || true
          done

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
      - run: dotnet test --no-build --verbosity normal
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        with:
          name: bithub-dotnet-build
          path: '**/bin/Release/**'
          retention-days: 7
        continue-on-error: true

      - name: Commit and PR changes
        run: |
          git add .github/workflows .gitcomply .gitenforcement .bit/config.bit.create || true
          if ! git diff --cached --quiet; then
            git -c user.name="bitbot" -c user.email="bitbot@users.noreply.github.com" commit -m "chore(bit.hub): compliance fixes"
            BRANCH="bitbot/compliance-fixes"
            git push -u origin HEAD:"$BRANCH" || true
            gh pr create --fill --title "Bit.Hub Compliance Fixes" --body "Automated fixes from BitBot workflow" || true
          else
            echo "::notice::No compliance changes needed."
          fi

  tos-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install conftest
        run: |
          wget -q https://github.com/open-policy-agent/conftest/releases/download/v0.45.0/conftest_0.45.0_Linux_x86_64.tar.gz -O conftest.tar.gz
          tar -xzf conftest.tar.gz
          sudo mv conftest /usr/local/bin/conftest

      - run: conftest test --policy .bithub/policies .

      - run: ./virtual.data.banks/audit_integrity_check.sh || true

      - run: |
          for f in ALN/**/*.lisp; do
            [ -f "$f" ] && echo "LISP check: $f"
          done

      - run: |
          for b in Batch/**/*.bat; do
            [ -f "$b" ] && echo "Batchfile check: $b"
          done

      - run: |
          for l in LOL_LANG/**/*.lol; do
            [ -f "$l" ] && echo "LOL.LANG audit: $l"
          done

      - run: |
          if [ -f "fan.asia/AIFantasia/validate.sh" ]; then
            bash fan.asia/AIFantasia/validate.sh
          fi

      - run: |
          if [ -f "virta-net/validate_net.sh" ]; then
            bash virta-net/validate_net.sh
          fi

      - run: |
          mkdir -p .bithub/audit_trail
          echo "Bit.Hub audit $(date) $(git rev-parse HEAD)" > .bithub/audit_trail/summary.log

      - uses: actions/upload-artifact@v4
        with:
          name: bithub-central-audit
          path: .bithub/audit_trail/
