name: Bit.Hub Meta Corrector v3 (Supremacy Alignment)

on:
  push:
    paths:
      - ".github/workflows/**"
      - ".bit/**"
      - ".bithub/**"
  schedule:
    - cron: "0 4 * * *" # daily alignment pass
  workflow_dispatch:
    inputs:
      auto_fix:
        description: "Open a PR with fixes"
        type: boolean
        default: true
      power_threshold:
        description: "standard | strict | paranoid"
        type: choice
        default: "strict"
        options: [ "standard", "strict", "paranoid" ]
      target_ref:
        description: "Base branch for PR"
        type: string
        default: "main"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: meta-corrector-v3-${{ github.ref }}
  cancel-in-progress: false

env:
  BIT_HUB_REPO_URL: "https://github.com/Doctor0Evil/Bit.Hub.git"
  REPORT_DIR: ".bithub/reports"
  POLICY_DIR: ".bithub/policy"
  SCHEMA_DIR: ".bit/schemas"
  POWER_THRESHOLD: ${{ inputs.power_threshold || vars.POWER_THRESHOLD || 'strict' }}
  CORRECTOR_BRANCH_PREFIX: "bot/workflow-corrections-v3"
  OPA_VERSION: "0.64.1"
  YQ_VERSION: "v4.44.3"

jobs:
  sync_policies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync canonical Bit.Hub policies (non-blocking)
        run: |
          set +e
          if git ls-remote "$BIT_HUB_REPO_URL" &>/dev/null; then
            git clone --depth=1 "$BIT_HUB_REPO_URL" /tmp/bithub
            rsync -av --ignore-existing /tmp/bithub/.bithub/policy/ .bithub/policy/
            rsync -av --ignore-existing /tmp/bithub/.bit/schemas/ .bit/schemas/
          else
            echo "::warning::Canonical repo unreachable — using local copies."
          fi
          set -e

  correct_and_audit:
    runs-on: ubuntu-latest
    needs: sync_policies
    outputs:
      changes: ${{ steps.diff.outputs.changes }}
    steps:
      - uses: actions/checkout@v4

      - name: Install yq + OPA
        run: |
          BIN="$HOME/.local/bin"; mkdir -p "$BIN"
          curl -fsSL -o "$BIN/yq" "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64"
          curl -fsSL -o "$BIN/opa" "https://openpolicyagent.org/downloads/v${OPA_VERSION}/opa_linux_amd64_static"
          chmod +x "$BIN/yq" "$BIN/opa"
          echo "$BIN" >> $GITHUB_PATH

      - name: Normalize and fix workflows
        run: |
          shopt -s nullglob
          for y in .github/workflows/*.y*ml; do
            yq -i 'if has("name") then . else .name = "Auto-Normalized Workflow" end' "$y"
            yq -i '.permissions = (.permissions // {"contents":"read"})' "$y"
            yq -i '.concurrency = (.concurrency // {"group": "wf-${{ github.ref }}", "cancel-in-progress": false})' "$y"
            yq -i '.jobs |= with_entries(.value."timeout-minutes" = (.value."timeout-minutes" // 30 | tonumber))' "$y"
            yq -i '.jobs |= with_entries(.value."runs-on" = (.value."runs-on" // ["self-hosted","bit.hub","linux"]))' "$y"
            yq -i '.jobs |= with_entries(.value.runs_on_adaptive = true)' "$y"
            yq -i '.. | select(tag == "!!str") |= sub("actions/checkout@v[12]"; "actions/checkout@v4")' "$y"
          done

      - name: Stage changes
        id: diff
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

  propose_changes:
    needs: correct_and_audit
    if: needs.correct_and_audit.outputs.changes == 'true' && inputs.auto_fix == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git add -A
      - uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ env.CORRECTOR_BRANCH_PREFIX }}/${{ github.run_id }}
          base: ${{ inputs.target_ref || 'main' }}
          title: "Bit.Hub Supremacy Alignment v3"
          commit-message: "chore(bit.hub): align workflows to Supremacy standards"
          body: |
            Automated corrections to align workflows with Bit.Hub Supremacy CI/CD standards.
            Canonical repo: $BIT_HUB_REPO_URL
            Power threshold: $POWER_THRESHOLD
          labels: compliance, automation
          delete-branch: true

  enforce_threshold:
    needs: correct_and_audit
    if: ${{ env.POWER_THRESHOLD != 'standard' }}
    runs-on: ubuntu-latest
    steps:
      - name: Enforce policy by threshold
        run: |
          DENY=$(jq '[.deny[]] | length' "${REPORT_DIR}/meta-corrector-v3.ndjson" 2>/dev/null || echo 0)
          WARN=$(jq '[.warn[]] | length' "${REPORT_DIR}/meta-corrector-v3.ndjson" 2>/dev/null || echo 0)
          if [ "$DENY" -gt 0 ]; then
            echo "Policy denials: $DENY"
            exit 1
          fi
          if [ "${POWER_THRESHOLD}" = "paranoid" ] && [ "$WARN" -gt 0 ]; then
            echo "Warnings blocked in paranoid mode: $WARN"
            exit 1
          fi
          echo "Policy gate passed for threshold ${POWER_THRESHOLD}"

                      - name: Upload a Build Artifact
  uses: actions/upload-artifact@v4.6.2
  with:
    # Artifact name
    name: # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
    path: 
    # The desired behavior if no files are found using the provided path.
Available Options:
  warn: Output a warning but do not fail the action
  error: Fail the action with an error message
  ignore: Do not output any warnings or errors, the action does not fail

    if-no-files-found: # optional, default is warn
    # Duration after which artifact will expire in days. 0 means using default retention.
Minimum 1 day. Maximum 90 days unless changed from the repository settings page.

    retention-days: # optional
    # The level of compression for Zlib to be applied to the artifact archive. The value can range from 0 to 9: - 0: No compression - 1: Best speed - 6: Default compression (same as GNU Gzip) - 9: Best compression Higher levels will result in better compression, but will take longer to complete. For large files that are not easily compressed, a value of 0 is recommended for significantly faster uploads.

    compression-level: # optional, default is 6
    # If true, an artifact with a matching name will be deleted before a new one is uploaded. If false, the action will fail if an artifact for the given name already exists. Does not fail if the artifact does not exist.

    overwrite: # optional, default is false
    # If true, hidden files will be included in the artifact. If false, hidden files will be excluded from the artifact.

    include-hidden-files: # optional, default is false
          
