name: Bit.Hub Mirror Sync

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "7 * * * *"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: bithub-mirror-sync-${{ github.ref }}
  cancel-in-progress: false

jobs:
  mirror:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirrors (best-effort)
        env:
          MIRROR_1_URL: ${{ secrets.MIRROR_1_URL }}
          MIRROR_1_PAT: ${{ secrets.MIRROR_1_PAT }}
          MIRROR_2_URL: ${{ secrets.MIRROR_2_URL }}
          MIRROR_2_PAT: ${{ secrets.MIRROR_2_PAT }}
        run: |
          set +e
          for i in 1 2; do
            url_var="MIRROR_${i}_URL"; pat_var="MIRROR_${i}_PAT"
            url="${!url_var}"; pat="${!pat_var}"
            [ -z "$url" ] && continue
            echo "::notice::Mirroring to $url"
            git remote add "mirror$i" "$url" 2>/dev/null || git remote set-url "mirror$i" "$url"
            if [[ "$url" == http* ]]; then
              url_auth="${url/https:\/\//https:\/\/x-access-token:${pat}@}"
              git remote set-url "mirror$i" "$url_auth"
            fi
            git push --mirror "mirror$i" || echo "::warning::Mirror push failed: mirror$i"
          done
          set -e

      - name: Always succeed
        run: echo "Mirror sync completed."
        
  name: Bit.Hub Mirror Sync

                                   on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "7 * * * *"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: bithub-mirror-sync-${{ github.ref }}
  cancel-in-progress: false

jobs:
  mirror:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirrors (best-effort)
        env:
          MIRROR_1_URL: ${{ secrets.MIRROR_1_URL }}
          MIRROR_1_PAT: ${{ secrets.MIRROR_1_PAT }}
          MIRROR_2_URL: ${{ secrets.MIRROR_2_URL }}
          MIRROR_2_PAT: ${{ secrets.MIRROR_2_PAT }}
        run: |
          set +e
          for i in 1 2; do
            url_var="MIRROR_${i}_URL"; pat_var="MIRROR_${i}_PAT"
            url="${!url_var}"; pat="${!pat_var}"
            [ -z "$url" ] && continue
            echo "::notice::Mirroring to $url"
            git remote add "mirror$i" "$url" 2>/dev/null || git remote set-url "mirror$i" "$url"
            if [[ "$url" == http* ]]; then
              url_auth="${url/https:\/\//https:\/\/x-access-token:${pat}@}"
              git remote set-url "mirror$i" "$url_auth"
            fi
            git push --mirror "mirror$i" || echo "::warning::Mirror push failed: mirror$i"
          done
          set -e

      - name: Always succeed
        run: echo "Mirror sync completed."
