name: Bit.Hub Security and Compliance

on:
  push:
    branches: [ main, '**' ]
    paths:
      - '**'
  schedule:
    - cron: '7,37 * * * *'
  workflow_dispatch: {}

permissions:
  contents: write

env:
  SUMMARY_BANNER: "This run is governed by TERMS-OF-SERVICE.md and Bit.Hub manifests."
  ALLOW_NET_UPDATES: "true" # set to "false" to force offline defs only

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Visible terms and policy banner
        run: |
          echo "## Compliance Notice" >> "$GITHUB_STEP_SUMMARY"
          echo "${{ env.SUMMARY_BANNER }}" >> "$GITHUB_STEP_SUMMARY"
          test -f TERMS-OF-SERVICE.md || echo "::warning ::TERMS-OF-SERVICE.md missing; wall will scaffold."

      - name: Renamer Sentinel
        uses: ./.github/actions/renamer-sentinel
        continue-on-error: true

      - name: Compliance Harness (advisory)
        uses: ./.github/actions/legal-draft-harness
        continue-on-error: true

  definitions-update:
    runs-on: ubuntu-latest
    needs: preflight
    steps:
      - uses: actions/checkout@v4

      - name: Update security definitions
        id: defs
        shell: bash
        continue-on-error: true
        env:
          ALLOW_NET_UPDATES: ${{ env.ALLOW_NET_UPDATES }}
        run: |
          bash .bit/command-sheets/update-definitions.sh

      - name: Upload definition artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-definitions
          path: |
            .bit/security/definitions/
            .bit/security/rules/
            .bit/security/versions.txt

  security-scan:
    runs-on: ubuntu-latest
    needs: definitions-update
    steps:
      - uses: actions/checkout@v4

      - name: Security Guard (install tools best-effort)
        uses: ./.github/actions/security-guard
        continue-on-error: true

      - name: Run malware/virus scans
        id: scan
        shell: bash
        continue-on-error: true
        run: |
          bash .bit/command-sheets/scan-repo.sh

      - name: Summarize findings
        if: always()
        run: |
          echo "## Security Scan Summary" >> "$GITHUB_STEP_SUMMARY"
          test -f .bit/security/logs/clamav.txt && \
            { echo "### ClamAV" >> "$GITHUB_STEP_SUMMARY"; sed 's/^/    /' .bit/security/logs/clamav.txt | tail -n 100 >> "$GITHUB_STEP_SUMMARY"; } || true
          test -f .bit/security/logs/yara.txt && \
            { echo "### YARA" >> "$GITHUB_STEP_SUMMARY"; sed 's/^/    /' .bit/security/logs/yara.txt | tail -n 100 >> "$GITHUB_STEP_SUMMARY"; } || true

      - name: Upload scan artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-reports
          path: .bit/security/logs/

  cluster-propagation:
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
      - uses: actions/checkout@v4

      - name: Propagate to .bit.bots and clusters (non-blocking)
        continue-on-error: true
        run: |
          bash .bit/command-sheets/propagate-security.sh || true
          echo "::notice ::Propagation broadcast sent to .bit.bots, .bit-runners, and botbit workflows."

  celebration:
    runs-on: ubuntu-latest
    needs: cluster-propagation
    steps:
      - run: echo "🎉 Security and compliance wall executed. Runs remain successful by policy."
